build:
  version: "2.0"

cards:
  message: "Welcome to BonBank cards related QA APIs "
  contactDetails:
    name: "Massiel Tirado - QA Lead"
    email: "massiel@tirado.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267