build:
  version: "1.0"

cards:
  message: "Welcome to BonBank cards related prod APIs "
  contactDetails:
    name: "Morales Tirado - Product Owner"
    email: "morales@tirado.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721